$scriptNames = @"
service-monitor.sh
disk-analyzer.sh
log-analyzer.sh
backup-system.sh
package-manager.sh
kernel-updater.sh
ssh-manager.sh
firewall-setup.sh
system-inventory.sh
user-expiry-check.sh
bulk-user-create.sh
service-deps.sh
failed-logins.sh
zombie-killer.sh
temp-monitor.sh
raid-status.sh
grub-backup.sh
set-timezone.sh
swap-manager.sh
selinux-toggle.sh
locale-setter.sh
hostname-setter.sh
kernel-modules.sh
sysctl-optimizer.sh
udev-manager.sh
cron-backup.sh
logrotate-setup.sh
ntp-sync.sh
syslog-config.sh
umask-setter.sh
profile-manager.sh
motd-generator.sh
boot-optimizer.sh
module-blacklist.sh
service-optimizer.sh
tuned-activator.sh
sysstat-analyzer.sh
journalctl-helper.sh
coredump-manager.sh
ulimit-setter.sh
sudoers-helper.sh
pam-config.sh
ssh-lockout.sh
tty-config.sh
autofs-setup.sh
ldconfig-helper.sh
alternatives-setup.sh
rclocal-manager.sh
profile-sync.sh
cgroup-manager.sh
systemd-analyze.sh
fstab-helper.sh
mount-helper.sh
disk-expander.sh
fs-checker.sh
inode-checker.sh
quota-manager.sh
syslog-ng-helper.sh
calculator.sh
unit-converter.sh
timer.sh
reminder.sh
weather.sh
currency-converter.sh
qr-generator.sh
password-manager.sh
clipboard-manager.sh
system-monitor.sh
file-rename.sh
dir-sync.sh
image-convert.sh
pdf-merge.sh
video-meta.sh
audio-normalize.sh
contact-extract.sh
calendar-gen.sh
screenshot.sh
clipboard-history.sh
text-search.sh
file-compare.sh
checksum-verify.sh
archive-helper.sh
battery-monitor.sh
cpu-stress.sh
memory-test.sh
disk-benchmark.sh
network-test.sh
system-benchmark.sh
font-manager.sh
theme-changer.sh
wallpaper-set.sh
keyboard-layout.sh
mouse-config.sh
audio-control.sh
brightness-control.sh
power-manager.sh
bluetooth-helper.sh
printer-helper.sh
scanner-helper.sh
usb-manager.sh
cd-dvd-helper.sh
iso-manager.sh
vm-helper.sh
cloud-helper.sh
ssh-tunnel.sh
vnc-helper.sh
rdp-helper.sh
teamviewer-helper.sh
tic-tac-toe.sh
hangman.sh
quiz.sh
fortune-teller.sh
ascii-art.sh
text-adventure.sh
memory-game.sh
snake-game.sh
math-trainer.sh
wordle.sh
guess-number.sh
text-rpg.sh
star-wars.sh
game-of-life.sh
sudoku.sh
morse-code.sh
poetry-gen.sh
ascii-clock.sh
casino.sh
quote-gen.sh
auto-updater.sh
cron-job-manager.sh
file-organizer.sh
download-manager.sh
email-notifier.sh
log-rotate.sh
git-auto-commit.sh
docker-cleanup.sh
vm-manager.sh
ssl-cert-checker.sh
website-monitor.sh
cert-renewal.sh
log-cleanup.sh
db-backup-rotate.sh
git-sync.sh
docker-prune.sh
system-report.sh
config-deploy.sh
ssh-key-distributor.sh
cron-validator.sh
backup-verifier.sh
log-alerter.sh
disk-space-alert.sh
process-watcher.sh
network-test.sh
config-backup.sh
ssl-expiry-alert.sh
user-activity-report.sh
package-tracker.sh
security-patch.sh
log-parser.sh
syslog-forwarder.sh
mail-queue.sh
ftp-sync.sh
rsync-wrapper.sh
tar-helper.sh
zip-helper.sh
gpg-helper.sh
ssh-tunnel.sh
vpn-checker.sh
wake-on-lan.sh
screen-session.sh
tmux-manager.sh
process-killer.sh
service-restarter.sh
file-monitor.sh
dir-sync.sh
git-hook-manager.sh
ssl-generator.sh
password-rotator.sh
deploy-webapp.sh
ci-cd-pipeline.sh
container-monitor.sh
load-balancer-setup.sh
health-check.sh
aws-cli-wrapper.sh
k8s-manager.sh
terraform-helper.sh
ansible-helper.sh
jenkins-backup.sh
cloud-init.sh
container-health.sh
rollback-helper.sh
config-drift.sh
secret-rotation.sh
cost-estimator.sh
pipeline-notify.sh
env-validator.sh
tf-state.sh
k8s-optimize.sh
docker-build.sh
compose-manager.sh
k8s-cleanup.sh
helm-helper.sh
gitops-sync.sh
argo-helper.sh
vault-helper.sh
consul-helper.sh
nomad-helper.sh
packer-helper.sh
vagrant-helper.sh
puppet-helper.sh
chef-helper.sh
salt-helper.sh
gitlab-helper.sh
github-helper.sh
bitbucket-helper.sh
jira-helper.sh
slack-helper.sh
teams-helper.sh
csv-parser.sh
json-formatter.sh
log-parser.sh
data-migrator.sh
db-backup.sh
xml-to-json.sh
text-processor.sh
data-analyzer.sh
file-encoder.sh
regex-tester.sh
csv-to-json.sh
log-anomaly.sh
data-dedupe.sh
format-validator.sh
db-query.sh
file-splitter.sh
data-mask.sh
column-extract.sh
text-index.sh
pattern-counter.sh
data-sort.sh
data-merge.sh
data-filter.sh
data-sample.sh
data-transform.sh
data-validate.sh
data-compare.sh
data-stats.sh
data-normalize.sh
data-pivot.sh
password-generator.sh
file-encryptor.sh
malware-scanner.sh
port-scanner.sh
ssl-tester.sh
audit-system.sh
ssh-hardening.sh
rootkit-checker.sh
firewall-audit.sh
vulnerability-scanner.sh
file-integrity.sh
password-policy.sh
suspicious-files.sh
login-analyzer.sh
ssl-deploy.sh
patch-checker.sh
firewall-optimize.sh
compliance-check.sh
ssh-notify.sh
process-detector.sh
file-permissions.sh
suid-finder.sh
tripwire-helper.sh
aide-helper.sh
selinux-audit.sh
apparmor-helper.sh
chroot-manager.sh
jail-helper.sh
tls-scanner.sh
security-bench.sh
network-scanner.sh
speed-test.sh
vpn-manager.sh
traceroute-wrapper.sh
dns-checker.sh
whois-lookup.sh
torrent-manager.sh
proxy-tester.sh
mac-changer.sh
wifi-analyzer.sh
dns-flush.sh
bandwidth-monitor.sh
latency-test.sh
route-optimize.sh
mac-tracker.sh
service-scanner.sh
packet-analyze.sh
hosts-manager.sh
net-config-backup.sh
wifi-connect.sh
"@.Split("`n") | ForEach-Object {
    $trimmedName = $_.Trim()
    if ($trimmedName -ne "" -and $trimmedName -like "*.sh") {
        try {
            New-Item -Path $trimmedName -ItemType File -Force | Out-Null
            Write-Host "Created: ${trimmedName}" -ForegroundColor Green # Changed this line
        } catch {
            # Corrected line to avoid parsing error by using ${} for the variable
            Write-Host "Error creating ${trimmedName}: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
}; Write-Host "`nAll specified .sh files created." -ForegroundColor Cyan